name: Build and deploy Node.js app to Azure Web App - accessiblemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Build frontend and server
        run: npm run build
        env:
          VITE_OPENROUTE_API_KEY: ${{ secrets.OPENROUTE_API_KEY }}

      - name: Run tests
        run: npm run test --if-present --passWithNoTests
        env:
          VITE_OPENROUTE_API_KEY: ${{ secrets.OPENROUTE_API_KEY }}

      - name: Verify build output
        run: ls dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            dist/
            server/dist/
            server/package.json
            server/package-lock.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Set up Node.js for deployment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install server production dependencies
        working-directory: ./server
        run: npm ci --production

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'accessiblemap'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3DA38C7FF8A04996A214F49385593ABB }}
